### ISSUE TITLE
Aomi generate bug

### ISSUE THREAD

**Issue by ericfode** [Autodesk/aomi#85]
Reproduction
=====
Run 
`aomi seed`
twice 
with this file
```yaml
# -*-YAML-*-
secrets:
- generated:
    mount: 'cicd/clerk'
    path: 'testpath'
    keys:
    - name: 'username'
      method: 'words'
      overwrite: true
    - name: 'password'
      method: 'uuid'
```

Expected:
========
 The password is created the first time and the username is generated every time seed is run

Actual: 
======
Username and password are correctly generated the first time. The password is removed (and username is generated correctly) the second time.
